# Pandas Intro
___
- EG: `import pandas as pd`
- This is the industry standard in handling Tabular Data. So anything that Excel and CSV's can handle, Pandas can definitely handle it

In [1]:
# Time to import Pandas
import pandas as pd

- Let's load some Data. There's a couple of popular (**Functions**) ways how to read in Data that we need to be familiar with
    - We have: `pandas.read_csv()`, `pandas.read_excel()`
- We are using these Functions in order to read in this Data and place it into a Data Type called: `Data Frame` (We will cover that shortly)
But first: Let's Test the `pandas.read_csv()` Function

In [4]:
# Reading the File
# Now all of our Data is inside of a Data Frame
df = pd.read_csv('V:\Data Analytics Notes\Learning Material\Python\Python Files\Python_Data_Project\sample_data\california_housing_test.csv')

In [ ]:
# Running the Type Function on the Variable, we can see it's of Type: Data Frame
type(df)

pandas.core.frame.DataFrame

### Brief Introduction into Data Frames:
- Whenever we Create the above `Object`, (`pd.read_csv('...')` this Data Frame we need to name it into a Variable)
    - It's common when we are just doing one Data Frame, to name it `df`
- Data Frames are: Two-dimentional, size-mutable, potentially hertogeneous tabular data
    - Data Structure also contains labeled axes: IE: Rows and Columns
    - Arithmetic Operations align on both Row and Column Labels
    - Can be thought of as a dict-like container for Series Objects
    - This is the Primary Data Structure

In [ ]:
# As we can see below, the Data is laid out in Rows and Columns (like Excel)
# It also has an Index (Far left Column)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
# Let's start with the Columns first!
# Because it's a dict like Object, we can use a similar notation in order to access the Columns (lets access total_rooms)
# This Returns all the different Values inside that Column (Column Header is the Key:Column Values are the Values)

df['total_rooms']

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

In [ ]:
# Above is not the only way we can Access this Column Data, we can use dot notation (df.) to access it too
# We can explicitly call out the column name itself to get the Values as well (Will provide exactly the same Results)
df.total_rooms

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

- So we talked about accessing the Columns... but what about if we want to access the Index??
- Let's say we want to access the first item in `total_rooms`
    - Similar to that List Index, we can provide square brackets `[]` and then type in the Index Number to get the corresponding Value that we want to see from the named Column

In [9]:
df.total_rooms[0]

3885.0

In [11]:
# This is the other way to do it but we get the exact same Results. Doesn't matter which way we do it
df['total_rooms'][2999]

1765.0

- Now, let's access the Jobs Data that we will be using for the Project and pull it in so we can have a look at it
- It's currently hosted on HuggingFace Website which is used to Host a ton of different Data for free
    - [Data Jobs Dataset](huggingface.co/datasets/lukebarousse/data_jobs)
    - We could Download it and then use the `pd.read_csv()` Function like we did above to bring it into the Environment... but, there's a better way!
- We can access it directly from HuggingFace!
    - To load the Dataset from the Hub:
    - We have a `load_dataset` Import Function: We can provide the name of the Data Set and then Load it into the Environment (we will have to Install Data Sets first though!)
        - So let's do that!

In [ ]:
# Installing Data Sets (Since it's a Terminal Command, the below notation is how we do it)
!pip install datasets

Collecting datasets
  Downloading datasets-4.8.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in f:\users\neill\anaconda3\lib\site-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in f:\users\neill\anaconda3\lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=21.0.0 in f:\users\neill\anaconda3\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in f:\users\neill\anaconda3\lib\site-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in f:\users\neill\anaconda3\lib\site-packages (from datasets) (1.5.3)
Requirement already satisfied: requests>=2.32.2 in f:\users\neill\anaconda3\lib\site-packages (from datasets) (2.32.5)
Collecting httpx<1.0.0 (from datasets)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting tqdm>=4.66.3 (from datasets)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.7 kB ? eta -:--:--
     -------------------- ----------------- 30.7/57.7 kB 640.0 kB/s eta 0:00:01
     -------------------------------------- 57.7/57.7 kB 753.0 kB/s eta 0:00:00
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py311-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in f:\users\neill\anaconda3\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2023.10.0)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Downloading huggingface_hub-1.7.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in f:\users\neill\anaconda3\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in f:\users\neill\anaconda3\lib\site-packages (from datasets) (6.0.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in f:\users\neill\anaconda3\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in f:\users\neill\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (4.2.0)
Requirement already satisfied: certifi in f:\users\neill\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (2025.11.12)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in f:\users\neill\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (3.4)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: typer in f:\users\neill\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.17.4)
Requirement already satisfied: typing-extensions>=4.1.0 in f:\users\neill\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in f:\users\neill\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\users\neill\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.0.7)
Requirement already satisfied: colorama in f:\users\neill\anaconda3\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.1 in f:\users\neill\anaconda3\lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in f:\users\neill\anaconda3\lib\site-packages (from pandas->datasets) (2023.3.post1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in f:\users\neill\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in f:\users\neill\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in f:\users\neill\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in f:\users\neill\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in f:\users\neill\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.0.4)
Requirement already satisfied: propcache>=0.2.0 in f:\users\neill\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in f:\users\neill\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in f:\users\neill\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Requirement already satisfied: sniffio>=1.1 in f:\users\neill\anaconda3\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: click>=8.0.0 in f:\users\neill\anaconda3\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in f:\users\neill\anaconda3\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in f:\users\neill\anaconda3\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (13.3.5)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in f:\users\neill\anaconda3\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in f:\users\neill\anaconda3\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in f:\users\neill\anaconda3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.0)
Downloading datasets-4.8.3-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/526.8 kB ? eta -:--:--
   -------------- ------------------------- 194.6/526.8 kB 5.9 MB/s eta 0:00:01
   ---------------------------------------  522.2/526.8 kB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 526.8/526.8 kB 5.6 MB/s eta 0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
   ---------------------------------------- 0.0/73.5 kB ? eta -:--:--
   ---------------------------------------- 73.5/73.5 kB 4.2 MB/s eta 0:00:00
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.8 kB ? eta -:--:--
   ---------------------------------------- 78.8/78.8 kB 4.3 MB/s eta 0:00:00
Downloading huggingface_hub-1.7.2-py3-none-any.whl (618 kB)
   ---------------------------------------- 0.0/618.0 kB ? eta -:--:--
   ------------------------------------- - 593.9/618.0 kB 18.8 MB/s eta 0:00:01
   ---------------------------------------- 618.0/618.0 kB 9.8 MB/s eta 0:00:00
Downloading multiprocess-0.70.19-py311-none-any.whl (144 kB)
   ---------------------------------------- 0.0/144.5 kB ? eta -:--:--
   ---------------------------------------- 144.5/144.5 kB 8.4 MB/s eta 0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
   ---------------------------------------- 0.0/120.0 kB ? eta -:--:--
   ---------------------------------------- 120.0/120.0 kB 7.3 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.4 kB ? eta -:--:--
   ---------------------------------------- 78.4/78.4 kB 2.2 MB/s eta 0:00:00
Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl (31 kB)
Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   -------------- ------------------------- 1.3/3.7 MB 27.5 MB/s eta 0:00:01
   ----------------------------------- ---- 3.2/3.7 MB 34.3 MB/s eta 0:00:01
   ---------------------------------------  3.7/3.7 MB 38.9 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 26.0 MB/s eta 0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: xxhash, tqdm, hf-xet, h11, dill, multiprocess, httpcore, httpx, huggingface-hub, datasets
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.65.0
    Uninstalling tqdm-4.65.0:
      Successfully uninstalled tqdm-4.65.0
  Attempting uninstall: dill
    Found existing installation: dill 0.3.7
    Uninstalling dill-0.3.7:
      Successfully uninstalled dill-0.3.7
Successfully installed datasets-4.8.3 dill-0.4.1 h11-0.16.0 hf-xet-1.4.2 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.7.2 multiprocess-0.70.19 tqdm-4.67.3 xxhash-3.6.0

In [2]:
# Now, let's Import in data sets
from datasets import load_dataset

In [3]:
# And finally, let's download the Data
dataset = load_dataset('lukebarousse/data_jobs')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
# Now let's access it and because it's a Dictionary like Object we need that notation along with the Key Name which in this case is train
dataset['train']

Dataset({
    features: ['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills'],
    num_rows: 785741
})

In [ ]:
# Running the Type Function on this we get back a Dataset... we want it as a Data Frame, since that's how we will Load it into Pandas
type(dataset['train'])

datasets.arrow_dataset.Dataset

In [28]:
# To do this, we are going to Run a Method on this, that dataset actually has!
# We can transform it into a multitude of different things (csv, dict, etc) but we are going to Transform it into Pandas!
# And now, we have it Imported in as a Dataframe!!
df = dataset['train'].to_pandas()
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

- In the next Section we are going to look at how to inspect the Data!
- By Running things like `df.info()` and a whole host of other things!