# Example: Analyze Salaries
___
- As we seen previously, using the `Group By` is a very powerful way of Aggregating and Analyzing different Groups of Data
- Now to do a deeper dive and Analyze the US/Canadian Job Market, specifically looking at the key statistics (median, min, max, count) around these different Job Titles available within their Country

In [1]:
# Imports
import pandas as pd
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
# First off, let's look at the Top 20 Value Counts for the Countries that are Available by looking at the job_country Column
df['job_country'].value_counts().head(20)

United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: job_country, dtype: int64

In [12]:
# To find if a Country is anywhere in the Data, use:
df['job_country'].isin(['Antartica']).any()

False

In [ ]:
# Create a New Data Frame with only our Countries of choice Filtered for with that Job Data
us_jobs = df[df['job_country'] == 'United States']
canada_jobs = df[df['job_country'] == 'Canada']

In [ ]:
# Printing it out to Inspect the Data Frame
us_jobs

             job_title_short  ...                                    job_type_skills
0       Senior Data Engineer  ...                                               None
3              Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
5              Data Engineer  ...  {'cloud': ['gcp'], 'programming': ['python', '...
6       Senior Data Engineer  ...  {'cloud': ['gcp', 'bigquery'], 'databases': ['...
9             Data Scientist  ...  {'analyst_tools': ['excel'], 'cloud': ['azure'...
...                      ...  ...                                                ...
785673        Data Scientist  ...                                               None
785685          Data Analyst  ...  {'analyst_tools': ['excel'], 'programming': ['...
785692        Data Scientist  ...         {'programming': ['python', 'matlab', 'r']}
785703          Data Analyst  ...                                               None
785705          Data Analyst  ...  {'analyst_tools': ['tableau'], 'programming': ...

[206292 rows x 17 columns]

- Now we have the Data we need. We have 2 Data Frames, 1 for the US and 1 for Canada
- Now we can perform a Group By Aggregation in order to Analyze it for things like: **Median**, **Min**, **Max**, **Count**
    - Before we can do that though, in the salary_year_avg Column, there's a lot of NaN Values in there... these will need to be Filtered out first

In [26]:
# Filtering out the NaN Values in salary_year_avg for us_jobs
us_jobs = us_jobs[us_jobs['salary_year_avg'].notna()]

# Filtering out the NaN Values in salary_year_avg for canada_jobs
canada_jobs = canada_jobs[canada_jobs['salary_year_avg'].notna()]

In [ ]:
# Printing it out to Inspect the Data Frame
us_jobs

       job_title_short  ...                                    job_type_skills
92       Data Engineer  ...                 {'programming': ['sql', 'python']}
100     Data Scientist  ...  {'programming': ['sql', 'r', 'python'], 'webfr...
109       Data Analyst  ...  {'analyst_tools': ['alteryx', 'tableau'], 'pro...
116     Data Scientist  ...  {'analyst_tools': ['tableau'], 'libraries': ['...
146      Data Engineer  ...  {'libraries': ['hadoop', 'spark'], 'programmin...
...                ...  ...                                                ...
785563  Data Scientist  ...  {'analyst_tools': ['word', 'power bi', 'tablea...
785624   Data Engineer  ...  {'analyst_tools': ['alteryx', 'power bi', 'tab...
785641   Data Engineer  ...                                               None
785648  Data Scientist  ...  {'cloud': ['azure', 'snowflake'], 'libraries':...
785692  Data Scientist  ...         {'programming': ['python', 'matlab', 'r']}

[15766 rows x 17 columns]

- We have Successfully Filtered out the NaN Values
- Now we can do the Group By

In [55]:
# Group the US Job Data
us_jobs.groupby('job_title_short')['salary_year_avg'].agg(['median', 'min', 'max', 'count']).sort_values(by='median', ascending=False)

                             median      min       max  count
job_title_short
Senior Data Scientist      155000.0  55000.0  475000.0   1241
Machine Learning Engineer  150000.0  44408.5  315000.0    128
Senior Data Engineer       150000.0  45000.0  375000.0   1058
Data Scientist             130000.0  30000.0  960000.0   4553
Software Engineer          130000.0  48982.0  375000.0    157
Data Engineer              125000.0  23496.0  525000.0   2915
Cloud Engineer             116100.0  42000.0  221844.0     20
Senior Data Analyst        110000.0  35360.0  425000.0    913
Business Analyst            90000.0  35000.0  387460.0    431
Data Analyst                90000.0  25000.0  375000.0   4350

In [54]:
# Group the Canada Job Data
canada_jobs.groupby('job_title_short')['salary_year_avg'].agg(['median', 'min', 'max', 'count']).sort_values(by='median', ascending=False)

                             median      min       max  count
job_title_short
Machine Learning Engineer  149653.0  63000.0  325000.0     53
Cloud Engineer             130000.0  90000.0  204000.0      7
Senior Data Scientist      130000.0  54907.0  231000.0     28
Senior Data Engineer       125000.0  64800.0  200000.0     60
Software Engineer          125000.0  63000.0  225000.0     46
Data Scientist             122500.0  63000.0  350000.0     55
Senior Data Analyst        111175.0  67500.0  175000.0      7
Data Engineer              105000.0  60000.0  375000.0    167
Data Analyst                98500.0  49566.5  160000.0     31
Business Analyst            85000.0  60000.0  190000.0      9