# Advanced - Pandas: Accessing Data
___
- EG: `df.iloc[:], df.loc[:]`
- Now it's time to start diving into a lot of the Problems that we are going to be Solving for the final Project, so we save a lot of time when we get there and we don't have to do a lot of work
- Because of that, we are going to go over a quick overview of a lot of the different Problems and Insights that we are going to eventually solve
- Then finally moving into a new Method of Accessing Data beyond just using that `.iloc` Method into the `.loc` Method

### Quick Overview of what we are Solving with the Final Project
___
- From the POV of an Aspiring Data Analyst, we will be looking to Analyze Top Paying Roles and Skills in the Field of Data Science
- Looking at this from the Perspctive of a Daya Analyst from Canada with an Interest in the United States as well
    - Not only will we be selecting whatever specific Job Title we want to Analyze (Out of the 8 that are contained in the Data) - I will be looking at Data Analyst
    - But we will also be selecting whatever Country we want to Analyze and are interested in (I will be predominantly looking at Canada and the US)

### Problems we will be Solving with the Project
___
1. What are the Most Demanded Skills for Data Analysts?
    - Building a Visualization to show the Percent Demand of a Certain Skill for not only Data Analyst, but also Senior Data Analysts so we can compare them to each other
2. How are in-demand Skills Trending for Data Analysts?
    - Evaluating, how they Trended over 2023 for the Top 5 Skills
3. How well do Jobs and Skills Pay for Data Analysts?
    - Analyzing the Median Salary for all the Data Analyst, then Analyze the Top Trending Skills on what their Salary is (Spoiler: Python is one of the highest)
4. What is the most optimal Skill to Learn for Data Analysts?
    - For this, we won't just look at what a Skill is paying, we will look at how in demand is a Skill? Using a Scatter Plot, we will break it down further when we get there

### Back to Learning Pandas and Learning Python
- Let's set up the Imports and Data Loading as we have previously done before

In [6]:
# Imports
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [8]:
# To look at the first row of Data we can use
df.iloc[0]

job_title_short                                       Senior Data Engineer
job_title                Senior Clinical Data Engineer / Principal Clin...
job_location                                                 Watertown, CT
job_via                                                    via Work Nearby
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                       Texas, United States
job_posted_date                                        2023-06-16 13:44:15
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                            NaN
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                          Boehringer Ingelheim
job_skills                                                             NaN
job_type_skills                                                        NaN
Name: 0, dtype: object

In [9]:
# To look at the first 10 rows of Data we can use
df.iloc[0: 10]

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                                NaN
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
5         Data Engineer  ...  {'cloud': ['gcp'], 'programming': ['python', '...
6  Senior Data Engineer  ...  {'cloud': ['gcp', 'bigquery'], 'databases': ['...
7         Data Engineer  ...  {'cloud': ['gcp', 'azure', 'aws', 'bigquery', ...
8      Business Analyst  ...  {'analyst_tools': ['excel', 'powerpoint', 'pow...
9        Data Scientist  ...  {'analyst_tools': ['excel'], 'cloud': ['azure'...

[10 rows x 17 columns]

- This is a pretty good way of getting Data back but there are drawbacks
- If we want to get the first Column back, we would have to use the Index Notation of this as follows
    - This isn't too bad... but not great, what happens if we want the `job_work_from_home` Column?
    - We would have to Count inwards on how many Columns that is
        - Once we find it's the 6th one in, and remembering it's a Zero based Index so it'll be in position 5 then we can get the Results
- Now what happens if we want to Include Multiple Columns at the same time specifically looking at the Salary Values (`salary_rate`, `salary_year_avg`, `salary_hour_avg`)
    - This would be a mess to try and count over to them and to try and figure out where they live
- This is where the `.loc` Method comes into play and is waaaaaaaaay better!

In [ ]:
# This will Return, the first Column for the First 10 Rows
df.iloc[0:10, 0]

0    Senior Data Engineer
1            Data Analyst
2           Data Engineer
3           Data Engineer
4           Data Engineer
5           Data Engineer
6    Senior Data Engineer
7           Data Engineer
8        Business Analyst
9          Data Scientist
Name: job_title_short, dtype: str

In [11]:
# This will Return, the sixth Column for the First 10 Rows
df.iloc[0:10, 5]

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8    False
9     True
Name: job_work_from_home, dtype: bool

In [46]:
# Showcasing the .loc Method to get the Values from the Multiple Salary Columns
# Same Annotation as the iloc Method: First Part specifies the Row Index, Second Part defines the Columns
# Difference here is, we can use the Actual Column Names, instead of having to use the Index of those Columns and counting to find those Indexes. Can just reference the Columns directly
# As well as this, we can define multiple Columns and use the Range Notation (Slicing Method) to get all of the Columns back
# Get from the first one defined to the last one defined, as well as all the other ones in between
df.loc[0:10, 'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

- Problem is we got back a whole list of NaN Values which is very Useless
- We are unable to Interpret this... so we will actually need to get Data to Analyze
    - First, Filter it to include more Values. We will expand our Search Range, instead of only grabbing 10 Rows we will grab all
        - This can be done by just having a Colon in the Index position `df.loc(:)` (This is a Selct All)
    - Next, Filter out/Drop all the NaN Values so we only get back Rows with Meaningful Data
        - IMPORTANT!: We only want to do this for a specific Column and that's `salary_rate`
        - Because, you will never have data in both `salary_hour_avg` and `salary_year_avg`. One will always be NaN, in that case, we will never get any Results if we Drop all Nan Values
        - Since typically, if there's an Hourly Rate there won't be a Yearly Rate and vice versa

In [55]:
# Dropping all NaN Values and Running this without specifying a Column
df.loc[:, 'salary_rate':'salary_hour_avg'].dropna()

Empty DataFrame
Columns: [salary_rate, salary_year_avg, salary_hour_avg]
Index: []

In [56]:
# Dropping all NaN Values for a specific Column
df.loc[:, 'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]