# Pandas - Concat DataFrames
___
- EG: `pd.concat([df1, df2])`
- This Function makes it super simple in order to bring together multiple Documents
- We are going to be working on a super simple Example first, basically just to show the power of this Function
    - Here we have 2 Data Frames (Very similar to our Jobs Data Frame):
        - job_postings_jan
            - job_id, job_title, company, job_posted_date
        - job_postings_feb
            - job_id, job_title, company, job_posted_date
    - We want to go through and actually, **Combine** these 2 DataFrames
- If we were to **Merge** these 2 DataFrames together, which is not recomended, but if it was done, that's going to give a Result that is not really wanted
- We wanted to **Stack these DataFrames on top of each other**
    - Here we would have Created Completely New Columns and made the Data a lot wider and basically un-useable for what we need it for...
- Now **Concatanate**, shows that we can either Combine DataFrames that have either:
     1. All the same Columns: This is known as Appending Rows of DataFrames (This is what we are going to be Focussing on)
     2. Can also be used to Append Columns of the DataFrame, but that's getting more into **Merge** Operations and it's recommended you use `.merge()` instead for that

- `pandas.concat`
    - Function of Pandas
    - Call it by using `pd.concat()`
    - For this we Provide **Objects**
        - **Objects**: A Sequence or Mapping of Series or DataFrame Objects
        - Basically going to Provide it a List of the DataFrames
        - Other thing to Note ios that `axis=0` (Automatically Defaults to 0)
        - Basically, we are going to be Concatonating it by Appending the Rows of the DataFrames and not the Columns
        - Other thing to Note, is with **Copy** and it's Defaulted Automatically to **True**
            - Creates a Copy of these, so we don't have to worry about it Altering that Original DataFrame
- Now it's time to Combine these 2 DataFrames but first I have to Create them

In [ ]:
import pandas as pd

# DataFrame 1 - January Job Postings
job_postings_jan = pd.DataFrame(
    {
        'job_id': [1, 2, 3, 4, 5],
        'job_title': [
            'Data Scientist',
            'Data Analyst',
            'Machine Learning Engineer',
            'Data Scientist',
            'Data Engineer'
        ],
        'company': [
            'Company A',
            'Company B',
            'Company C',
            'Company D',
            'Company E'
        ],
        'job_posted_date': [
            '2024-01-02',
            '2024-01-07',
            '2024-01-14',
            '2024-01-19',
            '2024-01-24'
        ]
    },
    index=[0, 1, 2, 3, 4]
)

# DataFrame 2 - February Job Postings
job_postings_feb = pd.DataFrame(
    {
        'job_id': [6, 7, 8, 9, 10],
        'job_title': [
            'Data Scientist',
            'Data Analyst',
            'Machine Learning Engineer',
            'Data Scientist',
            'Data Engineer'
        ],
        'company': [
            'Company F',
            'Company G',
            'Company H',
            'Company I',
            'Company J'
        ],
        'job_posted_date': [
            '2024-02-05',
            '2024-02-09',
            '2024-02-12',
            '2024-02-18',
            '2024-02-22'
        ]
    },
    index=[0, 1, 2, 3, 4]
)

In [2]:
# Printing out the January Job Posting
job_postings_jan

   job_id                  job_title    company job_posted_date
0       1             Data Scientist  Company A      2024-01-02
1       2               Data Analyst  Company B      2024-01-07
2       3  Machine Learning Engineer  Company C      2024-01-14
3       4             Data Scientist  Company D      2024-01-19
4       5              Data Engineer  Company E      2024-01-24

In [3]:
# Printing out the February Job Posting 
job_postings_feb

   job_id                  job_title    company job_posted_date
0       6             Data Scientist  Company F      2024-02-05
1       7               Data Analyst  Company G      2024-02-09
2       8  Machine Learning Engineer  Company H      2024-02-12
3       9             Data Scientist  Company I      2024-02-18
4      10              Data Engineer  Company J      2024-02-22